[build-system]
requires = [
    'flit_core >=2,<4',
    'setuptools_scm',
    'pytoml',
    'wheel',
]
build-backend = 'flit_core.buildapi'

[tool.flit.metadata]
module = 'infercnvpy'
author = 'Gregor Sturm'
author-email = 'gregor.sturm@i-med.ac.at'
home-page = 'https://github.com/icbi-lab/infercnvpy'
description-file = "README.rst"
classifiers = [
    'License :: OSI Approved :: BSD License',
    'Development Status :: 4 - Beta',
    'Intended Audience :: Developers',
    'Intended Audience :: Science/Research',
    'Programming Language :: Python :: 3',
]
requires-python = '>= 3.8'
requires = [
    'anndata>=0.7.3',
    'scanpy>=1.6.0',
    'pandas>=1',
    'numpy>=1.20', # includes type annotations
    'tqdm>=4.42.0', # required for process_map
    # for getting the version
    'setuptools_scm',
    'pytoml',
    'gtfparse>=1.2.1',
    'pycairo>=1.20; sys_platform == "win32"',
    'leidenalg',
    'pyreadr'
]

[tool.flit.metadata.requires-extra]
copykat = [
    'rpy2'
]
test = [
    'pytest',
    'black',
    'pre-commit',
]
doc = [
    'sphinx>=4.2',
    'sphinx_rtd_theme>=0.4',
    'scanpydoc[typehints]>=0.7.5',
    'docutils<0.18',
    # for tutorial
    'nbsphinx>=0.6.0,!=0.8.8', # https://github.com/spatialaudio/nbsphinx/issues/620, should be patched in >=0.8.9
    'jupytext',
    'sphinxcontrib-bibtex>=1.0.0',
    'pycairo',
    'jupyter_client',
    'ipykernel',
]

[tool.flit.metadata.urls]
Documentation = 'https://icbi-lab.github.io/infercnvpy/'

[tool.pytest.ini_options]
minversion = 6.0
testpaths = 'infercnvpy/tests'
norecursedirs = [ '.*', 'build', 'dist', '*.egg', 'data', '__pycache__']

[tool.setuptools_scm]
git_describe_command = "git describe --dirty --tags --long --match v*.*.*"
